# ============================================================================
# docker-compose.yml
# ============================================================================
version: '3.8'

services:
  # FastAPI service
  api:
    build: .
    container_name: text-summarizer-api
    ports:
      - "8000:8000"
    volumes:
      - ./artifacts:/app/artifacts
    environment:
      - MODEL_PATH=/app/artifacts/model_trainer/final_model
    command: python app.py
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
  
  # Gradio service
  demo:
    build: .
    container_name: text-summarizer-demo
    ports:
      - "7860:7860"
    volumes:
      - ./artifacts:/app/artifacts
    environment:
      - MODEL_PATH=/app/artifacts/model_trainer/final_model
    command: python gradio_app.py
    restart: unless-stopped