# ============================================================================
# config/config.yaml
# ============================================================================

artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  cache_dir: artifacts/data_ingestion/cache
  dataset_name: abisee/cnn_dailymail
  config_name: "3.0.0" # null | Optional: for datasets with multiple configs
  split: train
  max_samples: null  # Set to number (e.g., 100) for testing with subset
  #hf_streaming: false  # Set true for large datasets