# ============================================================================
# config/config.yaml
# ============================================================================
artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/ashaduzzaman-sarker/xsum.zip 
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
  # HuggingFace dataset config
  dataset_name: "abisee/cnn_dailymail"  # or "cnn_dailymail", "xsum", etc.
  dataset_split: "train"  # train, validation, test
  use_huggingface: false  # Set to true to use HuggingFace datasets